//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Routing_Server.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getContracts", ReplyAction="http://tempuri.org/IService1/getContractsResponse")]
        string getContracts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getContracts", ReplyAction="http://tempuri.org/IService1/getContractsResponse")]
        System.Threading.Tasks.Task<string> getContractsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getStations", ReplyAction="http://tempuri.org/IService1/getStationsResponse")]
        string getStations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getStations", ReplyAction="http://tempuri.org/IService1/getStationsResponse")]
        System.Threading.Tasks.Task<string> getStationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getStationsByContractName", ReplyAction="http://tempuri.org/IService1/getStationsByContractNameResponse")]
        string getStationsByContractName(string contractName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getStationsByContractName", ReplyAction="http://tempuri.org/IService1/getStationsByContractNameResponse")]
        System.Threading.Tasks.Task<string> getStationsByContractNameAsync(string contractName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Routing_Server.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Routing_Server.ServiceReference1.IService1>, Routing_Server.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getContracts() {
            return base.Channel.getContracts();
        }
        
        public System.Threading.Tasks.Task<string> getContractsAsync() {
            return base.Channel.getContractsAsync();
        }
        
        public string getStations() {
            return base.Channel.getStations();
        }
        
        public System.Threading.Tasks.Task<string> getStationsAsync() {
            return base.Channel.getStationsAsync();
        }
        
        public string getStationsByContractName(string contractName) {
            return base.Channel.getStationsByContractName(contractName);
        }
        
        public System.Threading.Tasks.Task<string> getStationsByContractNameAsync(string contractName) {
            return base.Channel.getStationsByContractNameAsync(contractName);
        }
    }
}
